#游戏界面
from enum import Enum
BLOCK=60
GAME_WIDTH=13*BLOCK
GAME_HEIGHT=13*BLOCK
#信息界面
INFO_WIDTH=3*BLOCK
INFO_HEIGHT=GAME_HEIGHT
#窗体
WINDOW_PADDING=8
WINDOW_WIDTH=GAME_WIDTH+INFO_WIDTH+3*WINDOW_PADDING
WINDOW_HEIGHT=GAME_HEIGHT+2*WINDOW_PADDING



class Direction(Enum):
    NONE=-1
    UP=0
    DOWN=1
    LEFT=2
    RIGHT=3